from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '0027'
down_revision = '0026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Tambah kolom last_active_at dengan timezone (TIMESTAMPTZ)
    # NULL dulu, nanti di-update
    op.add_column(
        'users', 
        sa.Column(
            'last_active_at', 
            sa.DateTime(timezone=True), 
            nullable=True
        )
    )
    
    # Update existing users dengan nilai NOW()
    op.execute(text(
        "UPDATE users SET last_active_at = NOW() WHERE last_active_at IS NULL"
    ))
    
    # Optional: Ubah menjadi NOT NULL setelah semua data terisi
    # op.alter_column('users', 'last_active_at', nullable=False)
    
    # Tambah index untuk performa query
    op.create_index(
        'ix_users_last_active_at', 
        'users', 
        ['last_active_at'], 
        unique=False
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Hapus index jika ada
    op.drop_index('ix_users_last_active_at', table_name='users')
    
    # Hapus kolom last_active_at
    op.drop_column('users', 'last_active_at')
    
    # ### end Alembic commands ###