from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0033'
down_revision = '0032'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE job_views
        ADD COLUMN user_id BIGINT NULL,
        ADD COLUMN user_agent TEXT NULL
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE job_views
        DROP COLUMN user_agent,
        DROP COLUMN user_id
        """
    )
    # ### end Alembic commands ###