"""add reminders table

Revision ID: 7c9f5b9f4268
Revises: 
Create Date: 2025-12-08 17:50:10.449713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9f5b9f4268'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('task_title', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.Enum('message', 'candidate', 'job_update', 'interview', 'other', name='reminder_task_type'), nullable=False),
    sa.Column('redirect_url', sa.String(length=1024), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'done', 'ignored', name='reminder_task_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminder_tasks_due_at', 'reminder_tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_reminder_tasks_employer_id'), 'reminder_tasks', ['employer_id'], unique=False)
    op.create_index('ix_reminder_tasks_employer_status', 'reminder_tasks', ['employer_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reminder_tasks_employer_status', table_name='reminder_tasks')
    op.drop_index(op.f('ix_reminder_tasks_employer_id'), table_name='reminder_tasks')
    op.drop_index('ix_reminder_tasks_due_at', table_name='reminder_tasks')
    op.drop_table('reminder_tasks')
    # ### end Alembic commands ###
