"""initial migration

Revision ID: 9442eb22ec09
Revises: 
Create Date: 2025-12-10 13:35:35.584813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9442eb22ec09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=False),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('employee_size', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=False),
    sa.Column('twitter_url', sa.String(length=255), nullable=False),
    sa.Column('instagram_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
<<<<<<< HEAD:superjob-corporate-api/migrations_disabled/versions/9442eb22ec09_initial_migration.py
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
=======
    # op.create_table('users',
    # sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    # sa.Column('username', sa.String(length=255), nullable=False),
    # sa.Column('email', sa.String(length=255), nullable=False),
    # sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    # sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('email'),
    # sa.UniqueConstraint('username')
    # )
    # op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
>>>>>>> f96f7d576fcc676043a658f69ff2b6e4e2164c94:superjob-db-migrations/app/db/migrations/versions/fc7f08e1fa99_initial_migration.py
    op.create_table('company_reviews',
    sa.Column('id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('pros', sa.Text(), nullable=False),
    sa.Column('cons', sa.Text(), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('employment_status', sa.String(length=255), nullable=False),
    sa.Column('employment_duration', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_reviews_company_id'), 'company_reviews', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_reviews_created_at'), 'company_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_reviews_id'), 'company_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_company_reviews_rating'), 'company_reviews', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_reviews_rating'), table_name='company_reviews')
    op.drop_index(op.f('ix_company_reviews_id'), table_name='company_reviews')
    op.drop_index(op.f('ix_company_reviews_created_at'), table_name='company_reviews')
    op.drop_index(op.f('ix_company_reviews_company_id'), table_name='company_reviews')
    op.drop_table('company_reviews')
    # op.drop_index(op.f('ix_users_id'), table_name='users')
    # op.drop_table('users')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
